create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.user_profiles (
  supabase_id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  username_normalized text not null,
  email text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists user_profiles_username_normalized_key
  on public.user_profiles (username_normalized);

do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'trg_user_profiles_set_updated_at') then
    create trigger trg_user_profiles_set_updated_at
    before update on public.user_profiles
    for each row execute function public.set_updated_at();
  end if;
end $$;

alter table public.user_profiles enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_profiles' and policyname = 'user_profiles_self'
  ) then
    create policy user_profiles_self
    on public.user_profiles
    for all
    using (auth.uid() = supabase_id)
    with check (auth.uid() = supabase_id);
  end if;
end $$;

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  teacher_id uuid not null references auth.users(id) on delete cascade,
  roll_no integer not null,
  name text not null,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint students_teacher_roll_unique unique (teacher_id, roll_no)
);

create index if not exists idx_students_teacher_id
  on public.students (teacher_id);

do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'trg_students_set_updated_at') then
    create trigger trg_students_set_updated_at
    before update on public.students
    for each row execute function public.set_updated_at();
  end if;
end $$;

alter table public.students enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'students' and policyname = 'students_teacher_isolation'
  ) then
    create policy students_teacher_isolation
    on public.students
    for all
    using (auth.uid() = teacher_id)
    with check (auth.uid() = teacher_id);
  end if;
end $$;

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  teacher_id uuid not null references auth.users(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  date date not null,
  status text not null,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint attendance_status_check check (status in ('Present', 'Absent')),
  constraint attendance_teacher_date_student_unique unique (teacher_id, date, student_id)
);

create index if not exists idx_attendance_teacher_date
  on public.attendance (teacher_id, date);

do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'trg_attendance_set_updated_at') then
    create trigger trg_attendance_set_updated_at
    before update on public.attendance
    for each row execute function public.set_updated_at();
  end if;
end $$;

alter table public.attendance enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'attendance' and policyname = 'attendance_teacher_isolation'
  ) then
    create policy attendance_teacher_isolation
    on public.attendance
    for all
    using (auth.uid() = teacher_id)
    with check (auth.uid() = teacher_id);
  end if;
end $$;
