-- Add branches support
create table if not exists public.branches (
  id bigint generated by default as identity primary key,
  teacher_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint branches_teacher_name_unique unique (teacher_id, name)
);

create index if not exists idx_branches_teacher_id
  on public.branches (teacher_id);

do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'trg_branches_set_updated_at') then
    create trigger trg_branches_set_updated_at
    before update on public.branches
    for each row execute function public.set_updated_at();
  end if;
end $$;

alter table public.branches enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'branches' and policyname = 'branches_teacher_isolation'
  ) then
    create policy branches_teacher_isolation
    on public.branches
    for all
    using (auth.uid() = teacher_id)
    with check (auth.uid() = teacher_id);
  end if;
end $$;

-- Add branch_id to students table
alter table public.students 
add column if not exists branch_id bigint references public.branches(id) on delete restrict;

-- Drop old unique constraint and add new one with branch_id
alter table public.students 
drop constraint if exists students_teacher_roll_unique;

alter table public.students 
add constraint students_teacher_branch_roll_unique unique (teacher_id, branch_id, roll_no);

-- Add branch_id to attendance table  
alter table public.attendance
add column if not exists branch_id bigint references public.branches(id) on delete restrict;

-- Drop old unique constraint and add new one with branch_id
alter table public.attendance
drop constraint if exists attendance_teacher_date_student_unique;

alter table public.attendance 
add constraint attendance_teacher_branch_date_student_unique unique (teacher_id, branch_id, date, student_id);

-- Create index for performance
create index if not exists idx_attendance_teacher_branch_date
  on public.attendance (teacher_id, branch_id, date);

-- Backfill existing data with default branch
do $$
declare
  default_branch_id bigint;
begin
  -- Insert a default branch for each teacher that has students but no branches
  insert into public.branches (teacher_id, name)
  select distinct teacher_id, 'Default'
  from public.students s
  where not exists (
    select 1 from public.branches b 
    where b.teacher_id = s.teacher_id
  )
  on conflict (teacher_id, name) do nothing
  returning id into default_branch_id;

  -- If we inserted a default branch, update existing students to use it
  if default_branch_id is not null then
    update public.students 
    set branch_id = default_branch_id 
    where branch_id is null;
  end if;

  -- Update any remaining students with null branch_id to use their teacher's default branch
  update public.students s
  set branch_id = (
    select b.id 
    from public.branches b 
    where b.teacher_id = s.teacher_id and b.name = 'Default'
    limit 1
  )
  where s.branch_id is null;
end $$;

-- Make branch_id not nullable after backfill
alter table public.students 
alter column branch_id set not null;

alter table public.attendance 
alter column branch_id set not null;
